"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](fg:color_bg3)$os$username$shell$memory_usage$time[](fg:color_bg3)\
(
[](fg:color_red)$git_branch$git_commit$git_state$git_metrics[](fg:color_red)\
)(
[](color_blue)$c$rust$golang$nodejs$python$conda[](fg:color_blue)\
)(
$docker_context\
[ ](fg:color_bg1)\
)
[](color_yellow)$directory[ ](fg:color_yellow)\
$line_break\
$character
"""

palette = 'solarized_personalized'

[palettes.solarized]
color_fg0    = '#fdf6e3'    # foreground for text/icons (Solarized base3)
color_bg1    = '#073642'    # primary background behind status blocks (base02)
color_bg3    = '#586e75'    # slightly lighter divider/background (base01)

# Accent blocks — original Solarized hues
color_blue   = '#268bd2'    # blue: informational highlights (e.g., branch)
color_aqua   = '#2aa198'    # cyan: secondary info (e.g., shell or context)
color_green  = '#859900'    # green: success/state OK indicators
color_yellow = '#b58900'    # yellow: warnings or neutral counts
color_orange = '#cb4b16'    # orange: less-severe alerts or diffs added
color_red    = '#dc322f'    # red: errors/failures
color_purple = '#6c71c4'    # violet: miscellaneous emphasis

[palettes.solarized_personalized]  # I did this by desaturating the original Solarized colors by 0.35
color_fg0    = '#fdf6e3'    # foreground for text/icons (Solarized base3)
color_bg1    = '#073642'    # primary background behind status blocks (base02)
color_bg3    = '#586e75'    # slightly lighter divider/background (base01)

color_blue   = '#5183a7'    # blue: informational highlights (e.g., branch)
color_aqua   = '#4e7d79'    # cyan: secondary info (e.g., shell or context)
color_green  = '#717e1b'    # green: success/state OK indicators
color_yellow = '#957820'    # yellow: warnings or neutral counts
color_orange = '#a45c3d'    # orange: less-severe alerts or diffs added
color_red    = '#b25b5a'    # red: errors/failures
color_purple = '#6c71c4'    # violet: miscellaneous emphasis


[os]
disabled = false
style = "bg:color_bg3 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_bg3 fg:color_fg0"
style_root = "bg:color_bg3 fg:color_fg0"
format = '[ $user]($style)'

[shell]
disabled = false
format = '[[ $indicator ](fg:color_fg0 bg:color_bg3)]($style)'
style = 'bg:color_bg3'
fish_indicator = "󰈺 shell" 
bash_indicator = " shell"
zsh_indicator = "zsh shell" 
powershell_indicator = "󰨊 shell"
unknown_indicator = "? shell"

[memory_usage]
disabled = false
threshold = -1
format = '[[$symbol ${ram} (${ram_pct}) ](fg:color_fg0 bg:color_bg3)]($style)'
symbol = '󰍛'
style = 'bg:color_bg3'

[time]
disabled = false
time_format = " %m/%d   %R"
style = "bg:color_bg3"
format = '[[$time ](fg:color_fg0 bg:color_bg3)]($style)'


[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[󰉓 : $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = " 󰲋 "
# "development" = " 󰲋 "

[git_branch]
symbol = ""
style = "bg:color_red"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_red)]($style)'

[git_commit]
only_detached = true
commit_hash_length = 4
tag_disabled = false
tag_symbol = " "  # nf-oct-git-compare (consistent with nerd font)
style = "bg:color_red"
format = '[[ ($hash$tag) ](fg:color_fg0 bg:color_red)]($style)'

[git_state]
style = "bg:color_red"
format = '[[ ($state $progress_current/$progress_total) ](fg:color_fg0 bg:color_red)]($style)'
rebase = " REBASE"
merge = " MERGE"
revert = " REVERT"
cherry_pick = " PICK"  # nf-mdi-source-branch-check
bisect = " BISECT"
am = " AM"
am_or_rebase = " AM/REBASE"

[git_metrics]
disabled = false
only_nonzero_diffs = true
format = '[[ $added  $deleted ](fg:color_fg0 bg:color_red)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
version_format = "v${major}.${minor}"  
format = '[[ $symbol( $version )(env: $virtualenv) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_bg3)]($style)'

[conda]
symbol = "🅒"
style = "bg:color_blue"
format = '[[$symbol :($environment)](fg:color_fg0 bg:color_blue)]($style)'


[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
